title: "Roam & Care"
description: "We roam, so you can work, relax, or handle the unexpected."
theme: jekyll-theme-minimal

plugins:
  - jekyll-polyglot
  - jekyll-seo-tag
  - jekyll-sitemap

languages: ["en", "fr", "es", "pt", "it"]
default_lang: "en"
parallel_localization: true
url: "https://roam-and-care.github.io"

exclude_from_localization:
  - javascript
  - images
  - css
  - public
  - sitemap
  - CNAME

sass:
  sass_dir: _sass
